spring:
  config:
    location: classpath:/queries.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringJPA
    username: postgres
    password: kotreyjr10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
